# Generated by Django 5.1.5 on 2025-04-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profiles/'),
        ),
    ]
