# Generated by Django 5.1.5 on 2025-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_buyerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profiles/'),
        ),
    ]
