# Generated by Django 5.1.5 on 2025-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driverprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
    ]
