# Generated by Django 5.1.5 on 2025-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_driverrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='product_approval_status',
        ),
        migrations.RemoveField(
            model_name='artisanprofile',
            name='product_category',
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='pending_approval_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='artisan_profiles/'),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
