# Generated by Django 5.1.5 on 2025-04-15 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('condition', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trash_point', models.CharField(default='', max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='waste_images/')),
                ('location', models.CharField(default='', max_length=255)),
                ('product_status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='', max_length=20)),
                ('delivery_status', models.CharField(choices=[('ready', 'Ready'), ('packed', 'Packed'), ('on_the_way', 'On its way'), ('delivered', 'Delivered')], default='', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcycledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('approval_status', models.BooleanField(default=False)),
                ('stock_availability', models.IntegerField()),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='upcycled_products/')),
                ('location', models.CharField(default='', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sold_count', models.IntegerField(default=0)),
                ('delivery_status', models.CharField(choices=[('ready', 'Ready'), ('packed', 'Packed'), ('on_the_way', 'On its way'), ('delivered', 'Delivered')], default='ready', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcycled_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
