# Generated by Django 5.1.5 on 2025-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_add_artisan_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcycledproduct',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
