# Generated by Django 5.2 on 2025-04-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_order_delivery_status_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
