# Generated by Django 5.2 on 2025-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('ready', 'Ready to Ship'), ('packed', 'Packed'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ready', max_length=20),
        ),
    ]
