# Generated by Django 5.2 on 2025-04-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
