# Generated by Django 5.2 on 2025-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashitem',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
